name: nest
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  app_links: ^6.4.1
  chewie: ^1.12.1
  crypto: ^3.0.6
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  flutter_web_auth_2: ^4.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  logger: ^1.4.0
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - .env
