import 'package:nest/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:nest/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:nest/ui/views/home/home_view.dart';
import 'package:nest/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:nest/ui/views/interest_selection/interest_selection_view.dart';
import 'package:nest/ui/views/location/location_view.dart';
import 'package:nest/ui/views/login/login_view.dart';
import 'package:nest/ui/views/register/register_view.dart';
import 'package:nest/ui/views/discover/discover_view.dart';
import 'package:nest/ui/views/hosting/hosting_view.dart';
import 'package:nest/ui/views/messages/messages_view.dart';
import 'package:nest/ui/views/tickets/tickets_view.dart';
import 'package:nest/ui/views/profile/profile_view.dart';
import 'package:nest/ui/views/navigation/navigation_view.dart';
import 'package:nest/services/global_service.dart';
import 'package:nest/ui/views/edit_profile/edit_profile_view.dart';
import 'package:nest/ui/views/event_activity/event_activity_view.dart';
import 'package:nest/ui/views/chat/chat_view.dart';
import 'package:nest/ui/views/create_post/create_post_view.dart';
import 'package:nest/services/image_service.dart';
import 'package:nest/ui/bottom_sheets/image_source/image_source_sheet.dart';
import 'package:nest/ui/bottom_sheets/add_location/add_location_sheet.dart';
import 'package:nest/ui/bottom_sheets/tag_people/tag_people_sheet.dart';
import 'package:nest/ui/views/discover_find_people/discover_find_people_view.dart';
import 'package:nest/ui/dialogs/comments/comments_dialog.dart';
import 'package:nest/ui/bottom_sheets/share/share_sheet.dart';
import 'package:nest/ui/bottom_sheets/report/report_sheet.dart';
import 'package:nest/ui/views/create_event/create_event_view.dart';
import 'package:nest/ui/views/upcoming/upcoming_view.dart';
import 'package:nest/ui/views/for_you/for_you_view.dart';
import 'package:nest/ui/views/following/following_view.dart';
import 'package:nest/ui/bottom_sheets/fin_events/fin_events_sheet.dart';
import 'package:nest/ui/views/explore_events/explore_events_view.dart';
import 'package:nest/ui/views/find_people_and_orgs/find_people_and_orgs_view.dart';
import 'package:nest/ui/views/view_event/view_event_view.dart';
import 'package:nest/services/websocket_service.dart';
import 'package:nest/services/message_service.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: InterestSelectionView),
    MaterialRoute(page: LocationView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: RegisterView),
    MaterialRoute(page: DiscoverView),
    MaterialRoute(page: HostingView),
    MaterialRoute(page: MessagesView),
    MaterialRoute(page: TicketsView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: NavigationView),
    MaterialRoute(page: EditProfileView),
    MaterialRoute(page: EventActivityView),
    MaterialRoute(page: ChatView),
    MaterialRoute(page: CreatePostView),
    MaterialRoute(page: DiscoverFindPeopleView),
    MaterialRoute(page: CreateEventView),
    MaterialRoute(page: UpcomingView),
    MaterialRoute(page: ForYouView),
    MaterialRoute(page: FollowingView),
    MaterialRoute(page: ExploreEventsView),
    MaterialRoute(page: FindPeopleAndOrgsView),
    MaterialRoute(page: ViewEventView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: GlobalService),
    LazySingleton(classType: ImageService),
    LazySingleton(classType: WebsocketService),
    LazySingleton(classType: MessageService),
// @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    StackedBottomsheet(classType: ImageSourceSheet),
    StackedBottomsheet(classType: AddLocationSheet),
    StackedBottomsheet(classType: TagPeopleSheet),
    StackedBottomsheet(classType: ShareSheet),
    StackedBottomsheet(classType: ReportSheet),
    StackedBottomsheet(classType: FinEventsSheet),
// @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    StackedDialog(classType: CommentsDialog),
// @stacked-dialog
  ],
)
class App {}
