import 'package:nest/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:nest/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:nest/ui/views/home/home_view.dart';
import 'package:nest/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:nest/ui/views/interest_selection/interest_selection_view.dart';
import 'package:nest/ui/views/location/location_view.dart';
import 'package:nest/ui/views/login/login_view.dart';
import 'package:nest/ui/views/register/register_view.dart';
import 'package:nest/ui/views/discover/discover_view.dart';
import 'package:nest/ui/views/hosting/hosting_view.dart';
import 'package:nest/ui/views/messages/messages_view.dart';
import 'package:nest/ui/views/tickets/tickets_view.dart';
import 'package:nest/ui/views/profile/profile_view.dart';
import 'package:nest/ui/views/navigation/navigation_view.dart';
import 'package:nest/services/global_service.dart';
import 'package:nest/ui/views/edit_profile/edit_profile_view.dart';
import 'package:nest/ui/views/event_activity/event_activity_view.dart';
import 'package:nest/ui/views/chat/chat_view.dart';
import 'package:nest/ui/views/create_post/create_post_view.dart';
import 'package:nest/services/image_service.dart';
import 'package:nest/ui/bottom_sheets/image_source/image_source_sheet.dart';
import 'package:nest/ui/bottom_sheets/add_location/add_location_sheet.dart';
import 'package:nest/ui/bottom_sheets/tag_people/tag_people_sheet.dart';
import 'package:nest/ui/views/discover_find_people/discover_find_people_view.dart';
import 'package:nest/ui/bottom_sheets/share/share_sheet.dart';
import 'package:nest/ui/bottom_sheets/report/report_sheet.dart';
import 'package:nest/ui/views/create_event/create_event_view.dart';
import 'package:nest/ui/views/upcoming/upcoming_view.dart';
import 'package:nest/ui/views/for_you/for_you_view.dart';
import 'package:nest/ui/views/following/following_view.dart';
import 'package:nest/ui/bottom_sheets/fin_events/fin_events_sheet.dart';
import 'package:nest/ui/views/explore_events/explore_events_view.dart';
import 'package:nest/ui/views/find_people_and_orgs/find_people_and_orgs_view.dart';
import 'package:nest/ui/views/view_event/view_event_view.dart';
import 'package:nest/services/websocket_service.dart';
import 'package:nest/services/message_service.dart';
import 'package:nest/services/api_service.dart';
import 'package:nest/services/auth_service.dart';
import 'package:nest/services/location_service.dart';
import 'package:nest/services/shared_preferences_service.dart';
import 'package:nest/ui/views/settings/settings_view.dart';
import 'package:nest/ui/dialogs/change_password/change_password_dialog.dart';
import 'package:nest/services/deep_link_service.dart';
import 'package:nest/services/deep_link_generator_service.dart';
import 'package:nest/services/share_service.dart';
import 'package:nest/services/user_service.dart';
import 'package:nest/services/file_service.dart';
import 'package:nest/ui/views/create_organization/create_organization_view.dart';
import 'package:nest/ui/dialogs/add_social/add_social_dialog.dart';
import 'package:nest/services/event_service.dart';
import 'package:nest/ui/dialogs/password_protected/password_protected_dialog.dart';
import 'package:nest/ui/bottom_sheets/tickets/tickets_sheet.dart';
import 'package:nest/ui/views/checkout/checkout_view.dart';
import 'package:nest/services/payment_service.dart';
import 'package:nest/services/stripe_service.dart';
import 'package:nest/services/social_service.dart';
import 'package:nest/ui/views/paymentweb/paymentweb_view.dart';
import 'package:nest/ui/dialogs/payment_successful/payment_successful_dialog.dart';
import 'package:nest/ui/bottom_sheets/comments/comments_sheet.dart';
import 'package:nest/services/comments_service.dart';
import 'package:nest/ui/views/analytics/analytics_view.dart';
import 'package:nest/ui/views/ticket_scanning/ticket_scanning_view.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: InterestSelectionView),
    MaterialRoute(page: LocationView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: RegisterView),
    MaterialRoute(page: DiscoverView),
    MaterialRoute(page: HostingView),
    MaterialRoute(page: MessagesView),
    MaterialRoute(page: TicketsView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: NavigationView),
    MaterialRoute(page: EditProfileView),
    MaterialRoute(page: EventActivityView),
    MaterialRoute(page: ChatView),
    MaterialRoute(page: CreatePostView),
    MaterialRoute(page: DiscoverFindPeopleView),
    MaterialRoute(page: CreateEventView),
    MaterialRoute(page: UpcomingView),
    MaterialRoute(page: ForYouView),
    MaterialRoute(page: FollowingView),
    MaterialRoute(page: ExploreEventsView),
    MaterialRoute(page: FindPeopleAndOrgsView),
    MaterialRoute(page: ViewEventView),
    MaterialRoute(page: SettingsView),
    MaterialRoute(page: CreateOrganizationView),
    MaterialRoute(page: CheckoutView),
    MaterialRoute(page: PaymentwebView),
    MaterialRoute(page: AnalyticsView),
    MaterialRoute(page: TicketScanningView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: GlobalService),
    LazySingleton(classType: ImageService),
    LazySingleton(classType: WebsocketService),
    LazySingleton(classType: MessageService),
    LazySingleton(classType: ApiService),
    LazySingleton(classType: AuthService),
    LazySingleton(classType: LocationService),
    InitializableSingleton(
      classType: SharedPreferencesService,
    ),
    LazySingleton(classType: DeepLinkService),
    LazySingleton(classType: DeepLinkGeneratorService),
    LazySingleton(classType: ShareService),
    LazySingleton(classType: UserService),
    LazySingleton(classType: FileService),
    LazySingleton(classType: EventService),
    LazySingleton(classType: PaymentService),
    LazySingleton(classType: StripeService),
    LazySingleton(classType: SocialService),
    LazySingleton(classType: CommentsService),
// @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    StackedBottomsheet(classType: ImageSourceSheet),
    StackedBottomsheet(classType: AddLocationSheet),
    StackedBottomsheet(classType: TagPeopleSheet),
    StackedBottomsheet(classType: ShareSheet),
    StackedBottomsheet(classType: ReportSheet),
    StackedBottomsheet(classType: FinEventsSheet),
    StackedBottomsheet(classType: TicketsSheet),
    StackedBottomsheet(classType: CommentsSheet),
// @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    StackedDialog(classType: ChangePasswordDialog),
    StackedDialog(classType: AddSocialDialog),
    StackedDialog(classType: PasswordProtectedDialog),
    StackedDialog(classType: PaymentSuccessfulDialog),
// @stacked-dialog
  ],
)
class App {}
