// Mocks generated by Mockito 5.4.5 from annotations
// in nest/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i16;
import 'dart:ui' as _i14;

import 'package:flutter/material.dart' as _i12;
import 'package:flutter_stripe/flutter_stripe.dart' as _i40;
import 'package:geolocator/geolocator.dart' as _i28;
import 'package:logger/logger.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:nest/abstractClasses/abstract_class.dart' as _i2;
import 'package:nest/abstractClasses/deep_link_handler_interface.dart' as _i30;
import 'package:nest/models/api_response.dart' as _i4;
import 'package:nest/models/create_event.dart' as _i38;
import 'package:nest/models/create_post.dart' as _i43;
import 'package:nest/models/login_model.dart' as _i26;
import 'package:nest/models/message_models.dart' as _i20;
import 'package:nest/models/organization_model.dart' as _i35;
import 'package:nest/models/payments.dart' as _i9;
import 'package:nest/models/places.dart' as _i5;
import 'package:nest/models/registration_model.dart' as _i25;
import 'package:nest/models/send_message_request.dart' as _i22;
import 'package:nest/models/update_profile_input.dart' as _i34;
import 'package:nest/services/api_service.dart' as _i23;
import 'package:nest/services/auth_service.dart' as _i24;
import 'package:nest/services/comments_service.dart' as _i44;
import 'package:nest/services/deep_link_generator_service.dart' as _i31;
import 'package:nest/services/deep_link_service.dart' as _i29;
import 'package:nest/services/event_service.dart' as _i37;
import 'package:nest/services/file_service.dart' as _i36;
import 'package:nest/services/global_service.dart' as _i15;
import 'package:nest/services/image_service.dart' as _i17;
import 'package:nest/services/location_service.dart' as _i27;
import 'package:nest/services/message_service.dart' as _i21;
import 'package:nest/services/payment_service.dart' as _i39;
import 'package:nest/services/share_service.dart' as _i32;
import 'package:nest/services/shared_coordinates_service.dart' as _i45;
import 'package:nest/services/shared_preferences_service.dart' as _i3;
import 'package:nest/services/social_service.dart' as _i42;
import 'package:nest/services/stripe_service.dart' as _i41;
import 'package:nest/services/user_service.dart' as _i33;
import 'package:nest/services/websocket_service.dart' as _i18;
import 'package:nest/ui/common/app_enums.dart' as _i19;
import 'package:nest/ui/views/ticket_scanning/ticket_scanning_viewmodel.dart'
    as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i6;
import 'package:stacked_services/stacked_services.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIApiService_0 extends _i1.SmartFake implements _i2.IApiService {
  _FakeIApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferencesService_1 extends _i1.SmartFake
    implements _i3.SharedPreferencesService {
  _FakeSharedPreferencesService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_2<T1> extends _i1.SmartFake
    implements _i4.ApiResponse<T1> {
  _FakeApiResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaceCoordinates_3 extends _i1.SmartFake
    implements _i5.PlaceCoordinates {
  _FakePlaceCoordinates_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_4 extends _i1.SmartFake
    implements _i6.SharedPreferences {
  _FakeSharedPreferences_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_5 extends _i1.SmartFake implements _i7.Logger {
  _FakeLogger_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanResult_6 extends _i1.SmartFake implements _i8.ScanResult {
  _FakeScanResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_7 extends _i1.SmartFake implements _i9.PaymentResult {
  _FakePaymentResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i10.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i12.GlobalKey<_i12.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i12.GlobalKey<_i12.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i10.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?>? navigateWithTransition<T>(
    _i12.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i12.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i10.Transition? transitionClass,
    _i10.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? replaceWithTransition<T>(
    _i12.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i12.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i10.Transition? transitionClass,
    _i10.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i12.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i12.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? navigateToView<T>(
    _i12.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i12.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i10.Transition? transition,
    _i10.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i12.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearStackAndShowView<T>(
    _i12.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearTillFirstAndShowView<T>(
    _i12.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i12.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i10.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i10.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i10.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i13.Future<_i10.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i13.Future<_i10.SheetResponse<dynamic>?>.value(),
      ) as _i13.Future<_i10.SheetResponse<dynamic>?>);

  @override
  _i13.Future<_i10.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i14.Color? barrierColor = const _i14.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i13.Future<_i10.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i13.Future<_i10.SheetResponse<T>?>.value(),
      ) as _i13.Future<_i10.SheetResponse<T>?>);

  @override
  void completeSheet(_i10.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i10.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i10.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i12.Widget Function(
      _i12.BuildContext,
      _i10.DialogRequest<dynamic>,
      dynamic Function(_i10.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i10.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i14.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i14.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i12.RouteSettings? routeSettings,
    _i12.GlobalKey<_i12.NavigatorState>? navigatorKey,
    _i10.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
      ) as _i13.Future<_i10.DialogResponse<dynamic>?>);

  @override
  _i13.Future<_i10.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i14.Color? barrierColor = const _i14.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i12.RouteSettings? routeSettings,
    _i12.GlobalKey<_i12.NavigatorState>? navigatorKey,
    _i12.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i13.Future<_i10.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i13.Future<_i10.DialogResponse<T>?>.value(),
      ) as _i13.Future<_i10.DialogResponse<T>?>);

  @override
  _i13.Future<_i10.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i14.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i14.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i12.RouteSettings? routeSettings,
    _i10.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
      ) as _i13.Future<_i10.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i10.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GlobalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGlobalService extends _i1.Mock implements _i15.GlobalService {
  @override
  int get otherUserId => (super.noSuchMethod(
        Invocation.getter(#otherUserId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set setOtherUserId(int? val) => super.noSuchMethod(
        Invocation.setter(
          #setOtherUserId,
          val,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get selectedHomeTabIndex => (super.noSuchMethod(
        Invocation.getter(#selectedHomeTabIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set setIndex(int? val) => super.noSuchMethod(
        Invocation.setter(
          #setIndex,
          val,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String getQueryParam(String? ext) => (super.noSuchMethod(
        Invocation.method(
          #getQueryParam,
          [ext],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getQueryParam,
            [ext],
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getQueryParam,
            [ext],
          ),
        ),
      ) as String);

  @override
  _i13.Future<dynamic> uploadFileGetURL(
    String? extension, {
    String? folder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFileGetURL,
          [extension],
          {#folder: folder},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  String getFileExtension(_i16.File? file) => (super.noSuchMethod(
        Invocation.method(
          #getFileExtension,
          [file],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getFileExtension,
            [file],
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getFileExtension,
            [file],
          ),
        ),
      ) as String);

  @override
  _i13.Future<dynamic> uploadFile(
    String? uploadUrl,
    _i16.File? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            uploadUrl,
            file,
          ],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i17.ImageService {
  @override
  _i13.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i16.File?> pickImageFromCamera() => (super.noSuchMethod(
        Invocation.method(
          #pickImageFromCamera,
          [],
        ),
        returnValue: _i13.Future<_i16.File?>.value(),
        returnValueForMissingStub: _i13.Future<_i16.File?>.value(),
      ) as _i13.Future<_i16.File?>);

  @override
  _i13.Future<_i16.File?> pickVideoFromCamera() => (super.noSuchMethod(
        Invocation.method(
          #pickVideoFromCamera,
          [],
        ),
        returnValue: _i13.Future<_i16.File?>.value(),
        returnValueForMissingStub: _i13.Future<_i16.File?>.value(),
      ) as _i13.Future<_i16.File?>);

  @override
  _i13.Future<_i16.File?> pickImageFromGallery() => (super.noSuchMethod(
        Invocation.method(
          #pickImageFromGallery,
          [],
        ),
        returnValue: _i13.Future<_i16.File?>.value(),
        returnValueForMissingStub: _i13.Future<_i16.File?>.value(),
      ) as _i13.Future<_i16.File?>);

  @override
  _i13.Future<_i16.File?> pickVideoFromGallery() => (super.noSuchMethod(
        Invocation.method(
          #pickVideoFromGallery,
          [],
        ),
        returnValue: _i13.Future<_i16.File?>.value(),
        returnValueForMissingStub: _i13.Future<_i16.File?>.value(),
      ) as _i13.Future<_i16.File?>);

  @override
  _i13.Future<List<_i16.File>> pickMultipleImages() => (super.noSuchMethod(
        Invocation.method(
          #pickMultipleImages,
          [],
        ),
        returnValue: _i13.Future<List<_i16.File>>.value(<_i16.File>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i16.File>>.value(<_i16.File>[]),
      ) as _i13.Future<List<_i16.File>>);
}

/// A class which mocks [WebsocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebsocketService extends _i1.Mock implements _i18.WebsocketService {
  @override
  _i13.Stream<_i19.WebSocketConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i13.Stream<_i19.WebSocketConnectionStatus>.empty(),
        returnValueForMissingStub:
            _i13.Stream<_i19.WebSocketConnectionStatus>.empty(),
      ) as _i13.Stream<_i19.WebSocketConnectionStatus>);

  @override
  _i13.Stream<_i20.MessagePayload> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i13.Stream<_i20.MessagePayload>.empty(),
        returnValueForMissingStub: _i13.Stream<_i20.MessagePayload>.empty(),
      ) as _i13.Stream<_i20.MessagePayload>);

  @override
  _i13.Stream<_i20.TypingPayload> get typingStream => (super.noSuchMethod(
        Invocation.getter(#typingStream),
        returnValue: _i13.Stream<_i20.TypingPayload>.empty(),
        returnValueForMissingStub: _i13.Stream<_i20.TypingPayload>.empty(),
      ) as _i13.Stream<_i20.TypingPayload>);

  @override
  _i13.Stream<_i20.OnlineStatusPayload> get onlineStatusStream =>
      (super.noSuchMethod(
        Invocation.getter(#onlineStatusStream),
        returnValue: _i13.Stream<_i20.OnlineStatusPayload>.empty(),
        returnValueForMissingStub:
            _i13.Stream<_i20.OnlineStatusPayload>.empty(),
      ) as _i13.Stream<_i20.OnlineStatusPayload>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i19.WebSocketConnectionStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _i19.WebSocketConnectionStatus.disconnected,
        returnValueForMissingStub: _i19.WebSocketConnectionStatus.disconnected,
      ) as _i19.WebSocketConnectionStatus);

  @override
  _i13.Future<void> connect(
    String? serverUrl,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            serverUrl,
            authToken,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<bool> sendMessage({
    required int? receiverId,
    required String? content,
    String? messageType = 'text',
    int? conversationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #receiverId: receiverId,
            #content: content,
            #messageType: messageType,
            #conversationId: conversationId,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> sendTypingIndicator({
    required int? conversationId,
    required bool? isTyping,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTypingIndicator,
          [],
          {
            #conversationId: conversationId,
            #isTyping: isTyping,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> markMessageAsRead({
    required int? messageId,
    required int? conversationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [],
          {
            #messageId: messageId,
            #conversationId: conversationId,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MessageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageService extends _i1.Mock implements _i21.MessageService {
  @override
  _i2.IApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
        returnValueForMissingStub: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.IApiService);

  @override
  _i19.WebSocketConnectionStatus get connectionStatus => (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i19.WebSocketConnectionStatus.disconnected,
        returnValueForMissingStub: _i19.WebSocketConnectionStatus.disconnected,
      ) as _i19.WebSocketConnectionStatus);

  @override
  Map<int, List<_i20.Message>> get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: <int, List<_i20.Message>>{},
        returnValueForMissingStub: <int, List<_i20.Message>>{},
      ) as Map<int, List<_i20.Message>>);

  @override
  Map<String, Set<int>> get typingUsers => (super.noSuchMethod(
        Invocation.getter(#typingUsers),
        returnValue: <String, Set<int>>{},
        returnValueForMissingStub: <String, Set<int>>{},
      ) as Map<String, Set<int>>);

  @override
  Map<int, bool> get onlineUsers => (super.noSuchMethod(
        Invocation.getter(#onlineUsers),
        returnValue: <int, bool>{},
        returnValueForMissingStub: <int, bool>{},
      ) as Map<int, bool>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<_i20.Message> getConversationMessages(int? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationMessages,
          [conversationId],
        ),
        returnValue: <_i20.Message>[],
        returnValueForMissingStub: <_i20.Message>[],
      ) as List<_i20.Message>);

  @override
  Set<int> getTypingUsers(int? conversationId) => (super.noSuchMethod(
        Invocation.method(
          #getTypingUsers,
          [conversationId],
        ),
        returnValue: <int>{},
        returnValueForMissingStub: <int>{},
      ) as Set<int>);

  @override
  bool isUserOnline(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #isUserOnline,
          [userId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<void> connect(
    String? serverUrl,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            serverUrl,
            authToken,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<bool> sendMessage({
    required int? receiverId,
    required String? content,
    String? messageType = 'text',
    int? conversationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #receiverId: receiverId,
            #content: content,
            #messageType: messageType,
            #conversationId: conversationId,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> sendTypingIndicator({
    required int? conversationId,
    required bool? isTyping,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTypingIndicator,
          [],
          {
            #conversationId: conversationId,
            #isTyping: isTyping,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> markMessageAsRead({
    required int? messageId,
    required int? conversationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [],
          {
            #messageId: messageId,
            #conversationId: conversationId,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  void addLocalMessage(
    int? conversationId,
    _i20.Message? message,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addLocalMessage,
          [
            conversationId,
            message,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setConversationMessages(
    int? conversationId,
    List<_i20.Message>? messages,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setConversationMessages,
          [
            conversationId,
            messages,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearConversationMessages(int? conversationId) => super.noSuchMethod(
        Invocation.method(
          #clearConversationMessages,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<dynamic> fetchConversations() => (super.noSuchMethod(
        Invocation.method(
          #fetchConversations,
          [],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> fetchConversationMessages(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchConversationMessages,
          [id],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> sendMessageApi(_i22.SendMessageRequest? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessageApi,
          [payload],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> createGroupConvo(dynamic body) => (super.noSuchMethod(
        Invocation.method(
          #createGroupConvo,
          [body],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i23.ApiService {
  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i3.SharedPreferencesService get prefsService => (super.noSuchMethod(
        Invocation.getter(#prefsService),
        returnValue: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
        returnValueForMissingStub: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
      ) as _i3.SharedPreferencesService);

  @override
  _i13.Future<_i4.ApiResponse<T>> get<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    T Function(dynamic)? parser,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #parser: parser,
          },
        ),
        returnValue:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<T>>);

  @override
  _i13.Future<_i4.ApiResponse<T>> post<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    T Function(dynamic)? parser,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
            #parser: parser,
          },
        ),
        returnValue:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<T>>);

  @override
  _i13.Future<_i4.ApiResponse<T>> put<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    T Function(dynamic)? parser,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
            #parser: parser,
          },
        ),
        returnValue:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<T>>);

  @override
  _i13.Future<_i4.ApiResponse<T>> delete<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    T Function(dynamic)? parser,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #parser: parser,
          },
        ),
        returnValue:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #queryParameters: queryParameters,
              #headers: headers,
              #parser: parser,
            },
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<T>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i24.AuthService {
  @override
  _i3.SharedPreferencesService get prefsService => (super.noSuchMethod(
        Invocation.getter(#prefsService),
        returnValue: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
        returnValueForMissingStub: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
      ) as _i3.SharedPreferencesService);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i13.Future<dynamic> register(_i25.RegistrationModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [model],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> requestChangePassword(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestChangePassword,
          [body],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> resetPassword(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [body],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<_i4.ApiResponse<dynamic>> sign(_i26.LoginModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [model],
        ),
        returnValue: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #sign,
            [model],
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #sign,
            [model],
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<dynamic>>);

  @override
  _i13.Future<Map<String, dynamic>> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue:
            _i13.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i13.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i13.Future<Map<String, dynamic>>);

  @override
  _i13.Future<Map<String, dynamic>> appleSignIn() => (super.noSuchMethod(
        Invocation.method(
          #appleSignIn,
          [],
        ),
        returnValue:
            _i13.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i13.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i13.Future<Map<String, dynamic>>);

  @override
  _i13.Future<_i4.ApiResponse<dynamic>> oAuthGoogle(
          {required Map<String, dynamic>? queryParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #oAuthGoogle,
          [],
          {#queryParams: queryParams},
        ),
        returnValue: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #oAuthGoogle,
            [],
            {#queryParams: queryParams},
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #oAuthGoogle,
            [],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<dynamic>>);

  @override
  _i13.Future<_i4.ApiResponse<dynamic>> oAuthApple(
          {required Map<String, dynamic>? queryParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #oAuthApple,
          [],
          {#queryParams: queryParams},
        ),
        returnValue: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #oAuthApple,
            [],
            {#queryParams: queryParams},
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #oAuthApple,
            [],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<dynamic>>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i27.LocationService {
  @override
  _i2.IApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
        returnValueForMissingStub: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.IApiService);

  @override
  _i13.Future<String?> getCurrentCity() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentCity,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
        returnValueForMissingStub: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<_i28.Position?> getCoordinatesFromCurrentLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoordinatesFromCurrentLocation,
          [],
        ),
        returnValue: _i13.Future<_i28.Position?>.value(),
        returnValueForMissingStub: _i13.Future<_i28.Position?>.value(),
      ) as _i13.Future<_i28.Position?>);

  @override
  _i13.Future<List<_i5.PlaceModel>> searchPlaces(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlaces,
          [query],
        ),
        returnValue:
            _i13.Future<List<_i5.PlaceModel>>.value(<_i5.PlaceModel>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i5.PlaceModel>>.value(<_i5.PlaceModel>[]),
      ) as _i13.Future<List<_i5.PlaceModel>>);

  @override
  _i13.Future<_i5.PlaceCoordinates> getPlaceCoordinates(String? placeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaceCoordinates,
          [placeId],
        ),
        returnValue:
            _i13.Future<_i5.PlaceCoordinates>.value(_FakePlaceCoordinates_3(
          this,
          Invocation.method(
            #getPlaceCoordinates,
            [placeId],
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i5.PlaceCoordinates>.value(_FakePlaceCoordinates_3(
          this,
          Invocation.method(
            #getPlaceCoordinates,
            [placeId],
          ),
        )),
      ) as _i13.Future<_i5.PlaceCoordinates>);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i3.SharedPreferencesService {
  @override
  _i6.SharedPreferences get preferences => (super.noSuchMethod(
        Invocation.getter(#preferences),
        returnValue: _FakeSharedPreferences_4(
          this,
          Invocation.getter(#preferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_4(
          this,
          Invocation.getter(#preferences),
        ),
      ) as _i6.SharedPreferences);

  @override
  _i13.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  String? getString(
    String? key, {
    String? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  _i13.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  int? getInt(
    String? key, {
    int? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  _i13.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  double? getDouble(
    String? key, {
    double? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  _i13.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  bool getBool(
    String? key, {
    bool? defaultValue = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  List<String>? getStringList(
    String? key, {
    List<String>? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStringList,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      ) as List<String>?);

  @override
  _i13.Future<bool> setObject(
    String? key,
    Map<String, dynamic>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setObject,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  Map<String, dynamic>? getObject(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getObject,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as Map<String, dynamic>?);

  @override
  _i13.Future<bool> setObjectList(
    String? key,
    List<Map<String, dynamic>>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setObjectList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  List<Map<String, dynamic>>? getObjectList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getObjectList,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as List<Map<String, dynamic>>?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> removeKeys(List<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #removeKeys,
          [keys],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  Set<String> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  Map<String, dynamic> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i13.Future<bool> setAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setExpiry(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setExpiry,
          [token],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> clearAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setIsLoggedIn(bool? isLoggedIn) => (super.noSuchMethod(
        Invocation.method(
          #setIsLoggedIn,
          [isLoggedIn],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  bool getIsLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #getIsLoggedIn,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<bool> setUserInfo(Map<String, dynamic>? userInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserInfo,
          [userInfo],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setAppSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAppSettings,
          [settings],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setFirstTimeLaunch(bool? isFirstTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFirstTimeLaunch,
          [isFirstTime],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  bool isFirstTimeLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstTimeLaunch,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<bool> setDarkMode(bool? isDarkMode) => (super.noSuchMethod(
        Invocation.method(
          #setDarkMode,
          [isDarkMode],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  bool getDarkMode() => (super.noSuchMethod(
        Invocation.method(
          #getDarkMode,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<bool> setLastKnownLocation(String? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastKnownLocation,
          [location],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> setBatch(Map<String, dynamic>? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBatch,
          [preferences],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  Map<String, dynamic> getBatch(List<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #getBatch,
          [keys],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [DeepLinkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkService extends _i1.Mock implements _i29.DeepLinkService {
  @override
  _i13.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void registerHandler(_i30.DeepLinkHandler? handler) => super.noSuchMethod(
        Invocation.method(
          #registerHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DeepLinkGeneratorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkGeneratorService extends _i1.Mock
    implements _i31.DeepLinkGeneratorService {}

/// A class which mocks [ShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareService extends _i1.Mock implements _i32.ShareService {
  @override
  dynamic copyToClipboard(String? resource) => super.noSuchMethod(
        Invocation.method(
          #copyToClipboard,
          [resource],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic getSharePostLink({
    required String? postId,
    required String? title,
    String? description,
    String? imageUrl,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getSharePostLink,
          [],
          {
            #postId: postId,
            #title: title,
            #description: description,
            #imageUrl: imageUrl,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i33.UserService {
  @override
  _i3.SharedPreferencesService get prefsService => (super.noSuchMethod(
        Invocation.getter(#prefsService),
        returnValue: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
        returnValueForMissingStub: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
      ) as _i3.SharedPreferencesService);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i13.Future<dynamic> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getOtherUserProfile(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getOtherUserProfile,
          [id],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getRecommendedUsers() => (super.noSuchMethod(
        Invocation.method(
          #getRecommendedUsers,
          [],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> searchUsers({
    required String? query,
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [],
          {
            #query: query,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getMyTickets() => (super.noSuchMethod(
        Invocation.method(
          #getMyTickets,
          [],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> editUserProfile(
          {required _i34.UpdateProfileInput? profileUpdateInput}) =>
      (super.noSuchMethod(
        Invocation.method(
          #editUserProfile,
          [],
          {#profileUpdateInput: profileUpdateInput},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getMyOrganization() => (super.noSuchMethod(
        Invocation.method(
          #getMyOrganization,
          [],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> searchOrganization({required String? q}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchOrganization,
          [],
          {#q: q},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getMyOrganizationAnalytics(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyOrganizationAnalytics,
          [id],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> createOrganization(
          {required _i35.Organization? organization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [],
          {#organization: organization},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> followUnfollowUser({
    required int? id,
    required bool? isFollow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #followUnfollowUser,
          [],
          {
            #id: id,
            #isFollow: isFollow,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<void> openSocialLink(String? url) => (super.noSuchMethod(
        Invocation.method(
          #openSocialLink,
          [url],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i36.FileService {
  @override
  _i7.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_5(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_5(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i7.Logger);

  @override
  set logger(_i7.Logger? _logger) => super.noSuchMethod(
        Invocation.setter(
          #logger,
          _logger,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i16.File> get selectedImages => (super.noSuchMethod(
        Invocation.getter(#selectedImages),
        returnValue: <_i16.File>[],
        returnValueForMissingStub: <_i16.File>[],
      ) as List<_i16.File>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i13.Future<void> pickImageFromCamera(_i19.FileType? fileType) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImageFromCamera,
          [fileType],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> pickImageFromGallery() => (super.noSuchMethod(
        Invocation.method(
          #pickImageFromGallery,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> pickMultipleImages() => (super.noSuchMethod(
        Invocation.method(
          #pickMultipleImages,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventService extends _i1.Mock implements _i37.EventService {
  @override
  _i3.SharedPreferencesService get prefsService => (super.noSuchMethod(
        Invocation.getter(#prefsService),
        returnValue: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
        returnValueForMissingStub: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
      ) as _i3.SharedPreferencesService);

  @override
  _i13.Future<dynamic> getMyEvents({
    required int? page,
    required int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyEvents,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getSingleEvent({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSingleEvent,
          [],
          {#id: id},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> searchEvents({
    required String? query,
    required int? page,
    required int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #query: query,
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getEventsNearMe({
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsNearMe,
          [],
          {
            #lat: lat,
            #lng: lng,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> createEvent(
          {required _i38.CreateEventRequest? requestBody}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {#requestBody: requestBody},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> validateTicketPassword({
    required String? password,
    required int? eventId,
    required int? ticketId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTicketPassword,
          [],
          {
            #password: password,
            #eventId: eventId,
            #ticketId: ticketId,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> createBooking({
    required int? eventId,
    required Map<String, dynamic>? requestBody,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBooking,
          [],
          {
            #eventId: eventId,
            #requestBody: requestBody,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<_i8.ScanResult> validateTicket({
    required String? qrData,
    int? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTicket,
          [],
          {
            #qrData: qrData,
            #eventId: eventId,
          },
        ),
        returnValue: _i13.Future<_i8.ScanResult>.value(_FakeScanResult_6(
          this,
          Invocation.method(
            #validateTicket,
            [],
            {
              #qrData: qrData,
              #eventId: eventId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i8.ScanResult>.value(_FakeScanResult_6(
          this,
          Invocation.method(
            #validateTicket,
            [],
            {
              #qrData: qrData,
              #eventId: eventId,
            },
          ),
        )),
      ) as _i13.Future<_i8.ScanResult>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i39.PaymentService {
  @override
  _i13.Future<_i9.PaymentResult> processPayment({
    required double? amount,
    required String? currency,
    required String? provider,
    required int? bookingId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processPayment,
          [],
          {
            #amount: amount,
            #currency: currency,
            #provider: provider,
            #bookingId: bookingId,
            #metadata: metadata,
          },
        ),
        returnValue: _i13.Future<_i9.PaymentResult>.value(_FakePaymentResult_7(
          this,
          Invocation.method(
            #processPayment,
            [],
            {
              #amount: amount,
              #currency: currency,
              #provider: provider,
              #bookingId: bookingId,
              #metadata: metadata,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i9.PaymentResult>.value(_FakePaymentResult_7(
          this,
          Invocation.method(
            #processPayment,
            [],
            {
              #amount: amount,
              #currency: currency,
              #provider: provider,
              #bookingId: bookingId,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i13.Future<_i9.PaymentResult>);

  @override
  _i13.Future<_i9.PaymentResult> processCustomPayment({
    required double? amount,
    required String? currency,
    required String? provider,
    required int? bookingId,
    required _i40.PaymentMethodParams? paymentMethodParams,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processCustomPayment,
          [],
          {
            #amount: amount,
            #currency: currency,
            #provider: provider,
            #bookingId: bookingId,
            #paymentMethodParams: paymentMethodParams,
            #metadata: metadata,
          },
        ),
        returnValue: _i13.Future<_i9.PaymentResult>.value(_FakePaymentResult_7(
          this,
          Invocation.method(
            #processCustomPayment,
            [],
            {
              #amount: amount,
              #currency: currency,
              #provider: provider,
              #bookingId: bookingId,
              #paymentMethodParams: paymentMethodParams,
              #metadata: metadata,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i9.PaymentResult>.value(_FakePaymentResult_7(
          this,
          Invocation.method(
            #processCustomPayment,
            [],
            {
              #amount: amount,
              #currency: currency,
              #provider: provider,
              #bookingId: bookingId,
              #paymentMethodParams: paymentMethodParams,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i13.Future<_i9.PaymentResult>);
}

/// A class which mocks [StripeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripeService extends _i1.Mock implements _i41.StripeService {
  @override
  _i2.IApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
        returnValueForMissingStub: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.IApiService);

  @override
  _i13.Future<_i9.PaymentIntent?> createPaymentIntent({
    required int? amount,
    required String? currency,
    required String? provider,
    required int? bookingId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentIntent,
          [],
          {
            #amount: amount,
            #currency: currency,
            #provider: provider,
            #bookingId: bookingId,
            #metadata: metadata,
          },
        ),
        returnValue: _i13.Future<_i9.PaymentIntent?>.value(),
        returnValueForMissingStub: _i13.Future<_i9.PaymentIntent?>.value(),
      ) as _i13.Future<_i9.PaymentIntent?>);

  @override
  _i13.Future<bool> confirmPayment(String? paymentIntentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [paymentIntentId],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i42.SocialService {
  @override
  _i3.SharedPreferencesService get prefsService => (super.noSuchMethod(
        Invocation.getter(#prefsService),
        returnValue: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
        returnValueForMissingStub: _FakeSharedPreferencesService_1(
          this,
          Invocation.getter(#prefsService),
        ),
      ) as _i3.SharedPreferencesService);

  @override
  _i13.Future<dynamic> createPost({required _i43.CreatePostRequest? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [],
          {#post: post},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> claudFlareSignVideo({int? maxDurationSeconds = 30}) =>
      (super.noSuchMethod(
        Invocation.method(
          #claudFlareSignVideo,
          [],
          {#maxDurationSeconds: maxDurationSeconds},
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getPosts({
    required int? page,
    required int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<dynamic> getUserPosts({
    required int? page,
    required int? size,
    required int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPosts,
          [],
          {
            #page: page,
            #size: size,
            #id: id,
          },
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);
}

/// A class which mocks [CommentsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsService extends _i1.Mock implements _i44.CommentsService {
  @override
  _i2.IApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
        returnValueForMissingStub: _FakeIApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.IApiService);

  @override
  dynamic getComments(int? postId) => super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic getMoreComments(
    int? postId, {
    required int? offset,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getMoreComments,
          [postId],
          {#offset: offset},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<dynamic> postComment(
    int? postId,
    String? commentText,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postComment,
          [
            postId,
            commentText,
          ],
        ),
        returnValue: _i13.Future<dynamic>.value(),
        returnValueForMissingStub: _i13.Future<dynamic>.value(),
      ) as _i13.Future<dynamic>);

  @override
  _i13.Future<_i4.ApiResponse<dynamic>> toggleLikeComment(int? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLikeComment,
          [commentId],
        ),
        returnValue: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #toggleLikeComment,
            [commentId],
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #toggleLikeComment,
            [commentId],
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<dynamic>>);

  @override
  _i13.Future<_i4.ApiResponse<dynamic>> toggleLikePost(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLikePost,
          [postId],
        ),
        returnValue: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #toggleLikePost,
            [postId],
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i4.ApiResponse<dynamic>>.value(
            _FakeApiResponse_2<dynamic>(
          this,
          Invocation.method(
            #toggleLikePost,
            [postId],
          ),
        )),
      ) as _i13.Future<_i4.ApiResponse<dynamic>>);
}

/// A class which mocks [SharedCoordinatesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedCoordinatesService extends _i1.Mock
    implements _i45.SharedCoordinatesService {}
